services:

  db:

    image: postgres

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: smart_access_management_system

    ports:

      - "5432:5432"

  app:

    build: .

    ports:

      - "8000:8000"

    environment:

      DATABASE_URL: postgresql://postgres:postgres@db:5432/smart_access_management_system

    env_file:

      - .env

    depends_on:

      - db