"""baseline schema

Revision ID: e1289f3287bc
Revises: 
Create Date: 2026-08-28 17:03:39.861478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1289f3287bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('person_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_activities_action'), 'person_activities', ['action'], unique=False)
    op.create_index(op.f('ix_person_activities_performed_by'), 'person_activities', ['performed_by'], unique=False)
    op.create_index(op.f('ix_person_activities_person_id'), 'person_activities', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_activities_timestamp'), 'person_activities', ['timestamp'], unique=False)
    op.create_table('terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('terminal_key', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminals_slug'), 'terminals', ['slug'], unique=False)
    op.create_index(op.f('ix_terminals_terminal_key'), 'terminals', ['terminal_key'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('registered_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index(op.f('ix_persons_created_at'), 'persons', ['created_at'], unique=False)
    op.create_index(op.f('ix_persons_registered_by_admin_id'), 'persons', ['registered_by_admin_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognition_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recognition_events')
    op.drop_table('notifications')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_persons_registered_by_admin_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_created_at'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_terminals_terminal_key'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_slug'), table_name='terminals')
    op.drop_table('terminals')
    op.drop_index(op.f('ix_person_activities_timestamp'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_person_id'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_performed_by'), table_name='person_activities')
    op.drop_index(op.f('ix_person_activities_action'), table_name='person_activities')
    op.drop_table('person_activities')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
